version: "3.8"

services:
  app:
    container_name: websocket_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    command: python app/server.py

  db:
    container_name: postgres_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
